name: 'CI Workflow'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env: 
      FOO: Foo value
      BAR: Baz value 

    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Setup uv 
        uses: astral-sh/setup-uv@v6

      - name : Linter 
        run : |
          uvx ruff check --fix
          uvx ruff format . 