name: 'CI Workflow'

on:
  pull_request:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env: 
      FOO: Foo value
      BAR: Baz value
      RUFF_OUTPUT_FORMAT: github

    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
